# Generated by Django 5.2.5 on 2025-08-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('dob', models.DateField(default='%m/%d/%Y')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=150)),
                ('genre', models.CharField(choices=[('FPS', 'FPS'), ('MOBA', 'MOBA'), ('Strategy', 'Strategy'), ('RPG', 'RPF'), ('Others', 'Others')], max_length=10)),
                ('rating', models.CharField(choices=[('PG', 'PG'), ('+14', '+14'), ('+16', '+16'), ('M', 'M')], max_length=3)),
            ],
        ),
    ]
