# Generated by Django 5.2.5 on 2025-08-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='quantity',
            field=models.PositiveIntegerField(default=1, max_length=3),
        ),
    ]
