# Generated by Django 5.2.5 on 2025-08-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0002_games_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1, max_length=3)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.customers')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamestore.games')),
            ],
        ),
    ]
